### ISSUE TITLE
availableSupply returns a string with commas

### ISSUE THREAD

**Issue by jyap808** [mess110/coinmarketcap.northpole.ro#1]
Can you change it to return an Integer instead?

**Comment by mess110** [comment]
How do you suggest I change it? Do you prefer a number or do you just want to get rid of the commas?

**Comment by jyap808** [comment]
Yeah, I just strip out the commas and cast an Integer client side.

availableSupply = int(availableSupply.replace(',', ''))

I think it makes more sense to make it an Integer.  String formatting can be done client side if required.

**Comment by jyap808** [comment]
Or maybe add availableSupplyNum to return a number for backwards compatibility.

**Comment by mess110** [comment]
I will make a 'dev' version in the future.

For now, I added a new field availableSupplyNumber, hope it helps.

Thanks for the feedback. As always, any suggestion welcome.
