### ISSUE TITLE
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by marcosjouron** [mess110/coinmarketcap.northpole.ro#11]
I would like to use the northpole api but i have a problem using ajax call to get the json i.e: http://coinmarketcap.northpole.ro/api/v6/history/BTC_2017.json i get:
"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource"
I read that it is a problem related with cross domains but i don't now how i can resolve it in my side.
Could you explain me why people use it from javascript it please?

Thx in advance @mess110

**Comment by mess110** [comment]
Yes, the previous request had CORS disabled, so you couldn't make the request.

I just released a new version. Please try with

http://coinmarketcap.northpole.ro/history.json?coin=BTC&year=2017

**Comment by mess110** [comment]
I tested it on JSBIN, but it would be great if you could confirm it works.

Thanks

**Comment by marcosjouron** [comment]
Hi Cristian, I just test it, and it works like a charm!!!
I checked out theese three:
url: "http://coinmarketcap.northpole.ro/history.json?coin=BTC&year=2017"
url: "http://coinmarketcap.northpole.ro/ticker.json?select=BTC,DOGE"
url: "http://coinmarketcap.northpole.ro/ticker.json?page=1&size=10"

Thanks very, very much I'm sure that many people will thanks you. You were very kind and fast.
I hope to be in touch with you.
Cheers.
