### ISSUE TITLE
History of the last 7 and 14 days

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#12]
Is there a way we can get a history endpoint that gives you all the data of the last 7 and 14 days, (with data of every hour)

**Comment by mess110** [comment]
Don't have data every hour, only have it at daily intervals or "now".

If you are interested, I can add a param for last x days.

**Comment by vanlooverenkoen** [comment]
That would be awesome as well. But what I realy wanted to do is to show a more detailed version of every hour. Is this possible to add this in a future update. You only need to keep the info for 14 days the rest can be deleted

**Comment by mess110** [comment]
http://coinmarketcap.northpole.ro/history.json?coin=BTC&period=14days&version=v7

**Comment by vanlooverenkoen** [comment]
the format of the date is wrong 

"date":"02-26-06-2017"
"date":"00-26-06-2017"
"date":"06-26-06-2017"
...

**Comment by mess110** [comment]
That is somewhat debatable. It could need improving, depending on what we discuss now.

The format is: `HH-dd-MM-YYYY`.

HH - Hour of the day, 24-hour clock, zero-padded (00..23)
dd - Day of the month, zero-padded (01..31)
MM - Month of the year, zero-padded
YYYY - Year with century (can be negative, 4 digits at least)
