### ISSUE TITLE
History JSON structure

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#13]
```
{
  "symbol": "BTC",
  "history": {
    "01-01-2017": {
      "position": 1,
      "name": "Bitcoin",
       ....
    }
  }
}
```

to this

```
{
  "symbol": "BTC",
  "history": [
      {
      "date":  "01-01-2017",
      "position": 1,
      "name": "Bitcoin",
       ....
    }
  ]
}

```

It would be a lot easier to handle in frontend applications. and you can sort in the backend on the date

**Comment by ekerstein** [comment]
If you do change it, just be careful because I have my web app configured for the current structure. I'm pulling v6.

**Comment by vanlooverenkoen** [comment]
Maybe we it is possible to pass an extra param for formatting in "my" structure

**Comment by mess110** [comment]
Since it would be a format which breaks existing clients, it will require a version bump. I will not break existing clients. At least not on purpose :)

I will see how I will handle this, the format does need improving.

**Comment by vanlooverenkoen** [comment]
That is fine with me. It would be v7 then I quess? If I could write ruby I would write it myself but I have no idea where to start. Any quickstart quides where I could learn how to write apis like you did

**Comment by mess110** [comment]
I am using an experimental framework I made called [ki](https://github.com/mess110/ki). You can read about it here. See app.rb, that is the code for the webapp.

One thing you could try is see if you can run the code locally.

Yes, it will be v7.

**Comment by mess110** [comment]
http://coinmarketcap.northpole.ro/history.json?coin=BTC&year=2017&version=v7
