### ISSUE TITLE
All Coins does not contain the same data as 1 Coin

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#14]
/coins.json

does not contain the same data as 

`/ticker.json?select=BTC`

The BTC data is different when you pull it at the same time. Can you fix this?

**Comment by mess110** [comment]
`/coins.json` returns metadata of the coins.

`/ticker.json` returns all coin data

`/ticker.json?select=BTC` returns BTC data

Maybe I misunderstood what you are asking for. Could you please give me an example?

**Comment by vanlooverenkoen** [comment]
OMG nvm I have been searching for it the whole day and it was something in my android application I forgot adding the , when selecting multiple coins ;) my bad
