### ISSUE TITLE
improve doc

### ISSUE THREAD

**Issue by mess110** [mess110/coinmarketcap.northpole.ro#17]

**Comment by jupiter50** [comment]
When deploying the code on a server, how is the new history.json created to pull in the right history? http://coinmarketcap.northpole.ro/history.json?coin=bitcoin&year=2017

It also looks like the JSON structure has changed from v6 to the new history.json:
v6:
{  
   "symbol":"BTC",
   "history":{  
      **"01-01-2017":{**  
         "position":1,
         "name":"Bitcoin",
         "symbol":"BTC",
         "category":"currency",
         "marketCap":{  
            "usd":15460877989.5,
            "btc":16075275.0,
            "eur":14693090788.541428,
            "cny":107371159373.68065,
            "gbp":12530036653.420433,
            "cad":20784676716.40443,
            "rub":947230789168.1038,
            "hkd":119896635068.09416,
            "jpy":1808451167992.8203,
            "aud":21468975176.2197
         },
         "price":{  
            "usd":961.78,
            "btc":1.0,
            "eur":914.0180051999998,
            "cny":6679.273566,
            "gbp":779.4601743000001,
            "cad":1292.9593252,
            "rub":58924.702013999995,
            "hkd":7458.450015199999,
            "jpy":112498.92571,
            "aud":1335.527708
         },
         "availableSupply":16075275,
         "volume24":{  
            "usd":99510567.7,
            "btc":103465.0,
            "eur":94568872.90801798,
            "cny":691071039.50619,
            "gbp":80646846.93394952,
            "cad":133776036.581818,
            "rub":6096644293.8785095,
            "hkd":771688530.8226678,
            "jpy":11639701348.58515,
            "aud":138180374.30822
         },
         "change1h":0.12,
         "change24h":0.32,
         "change7d":6.88,
         "timestamp":1483225202
      },
.....

history.json:

{  
   "symbol":"BTC",
   "history":[  
      {  
         "position":1,
         "name":"Bitcoin",
         "symbol":"BTC",
         "category":"currency",
         "marketCap":{  
            "usd":15460877989.5,
            "btc":16075275.0,
            "eur":14693090788.541428,
            "cny":107371159373.68065,
            "gbp":12530036653.420433,
            "cad":20784676716.40443,
            "rub":947230789168.1038,
            "hkd":119896635068.09416,
            "jpy":1808451167992.8203,
            "aud":21468975176.2197
         },
         "price":{  
            "usd":961.78,
            "btc":1.0,
            "eur":914.0180051999998,
            "cny":6679.273566,
            "gbp":779.4601743000001,
            "cad":1292.9593252,
            "rub":58924.702013999995,
            "hkd":7458.450015199999,
            "jpy":112498.92571,
            "aud":1335.527708
         },
         "availableSupply":16075275,
         "volume24":{  
            "usd":99510567.7,
            "btc":103465.0,
            "eur":94568872.90801798,
            "cny":691071039.50619,
            "gbp":80646846.93394952,
            "cad":133776036.581818,
            "rub":6096644293.8785095,
            "hkd":771688530.8226678,
            "jpy":11639701348.58515,
            "aud":138180374.30822
         },
         "change1h":0.12,
         "change24h":0.32,
         "change7d":6.88,
         "timestamp":1483225202,
         "date":"01-01-2017"
      },

The key difference is that in v6, each data object was within a "date" which meant people could easily pull out specific date data out of an array created from the JSON.

e.g data.history["01-01-2017"].price["USD"]

In the new history format, this no longer works and you have to go through all of the objects and data to eventually finding the right data for the date you want

v8 looks to work similarly to v6 as the structure is almost the same and data identified by date

**Comment by mess110** [comment]
I will add an option so you can choose which format you want.

Regarding history, the history is gathered once every day when the script runs.
