### ISSUE TITLE
Request: Can 'global' ticker data be made into a daily snapshot?

### ISSUE THREAD

**Issue by ekerstein** [mess110/coinmarketcap.northpole.ro#19]
The global ticker data is useful/interesting. Is there any way this can be made into a daily snapshot so that I could pull this same data for any day of the year?

```
"global": {
"total_market_cap":84460537173.50919,
"total_24h_volume":5822700275.020874,
"bitcoin_percent_of_market_cap":45.07,
"active_currencies":810,
"active_assets":174
}
```

**Comment by mess110** [comment]
Yea that would be a cool feature. Will implement
