### ISSUE TITLE
API stopped working

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#21]
http://coinmarketcap.northpole.ro/ticker.json?select=BTC,DOGE

Just stopped working. It returns an empty list market. Can you fix this as soon as possible? :)

**Comment by vanlooverenkoen** [comment]
I'am currently on vacation so I can't update my app. I will change it when I am back to identifier instead of select

**Comment by ekerstein** [comment]
Works for me. I get this:

`{"timestamp":1500602702,"markets":[],"currencyExchangeRates":{"usd":"1","aud":"0.7952058628937859","brl":"0.32031775521317146","cad":"0.7938996748980831","chf":"1.0509997635250532","cny":"0.14794978584268498","eur":"1.1627744729143314","gbp":"1.2966804979253113","hkd":"0.1280335960155945","idr":"7.503261179922936e-05","inr":"0.015543638765835083","jpy":"0.008937848436435138","krw":"0.0008915914014925241","mxn":"0.057151537644974874","rub":"0.01697072549851506"},"global":{"total_market_cap":94720273194.95676,"total_24h_volume":6072112090.997731,"bitcoin_percent_of_market_cap":48.48,"active_currencies":819,"active_assets":175}}`

**Comment by vanlooverenkoen** [comment]
It doesn't give an error code but the market list is empty. This worked last week. I guess it has something to do with the new identifiers you added three days ago.

**Comment by mess110** [comment]
Fixed, was a bug, thx for reporting.

**Comment by vanlooverenkoen** [comment]
Awesome, you saved my username today :) hahaha
