### ISSUE TITLE
Server does not update anymore.

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#23]
All responses have the same timestamp. They don't change.

1500980402

I don't know why? And how the timestamp is generated. Please take a look at this.

**Comment by vanlooverenkoen** [comment]
Also the data is never updated

**Comment by ekerstein** [comment]
Seems to have stopped on 7/25. For example if you look at http://coinmarketcap.northpole.ro/history.json?coin=bitcoin you'll see that's the most recent date.

**Comment by vanlooverenkoen** [comment]
Yes I know, but I can't restart them. So I'm stuck here.

**Comment by mess110** [comment]
is this still the case? Am on holiday, but I did a quick run by hand and I didn't get errors. Will monitor

**Comment by mess110** [comment]
Please leave any details you might have. Thx

**Comment by vanlooverenkoen** [comment]
There are no errors the data is just outdated. And hasn't been updated for 3 days.

**Comment by iwok** [comment]
I think there is a problem with the cronjob. Having issues getting the script running on my server. The command is executed by hand but not via the cronjob

**Comment by jupiter50** [comment]
The cron job using the latest code seems to work fine with the v6 API and populating the last few days. However, looks like it is updating at 5am UTC

**Comment by vanlooverenkoen** [comment]
When did you pull from the server?

**Comment by jupiter50** [comment]
A few days ago. Before that there was a bit of a data gap similar to what we are seeing on the main site so I tried upgrading the code on my server to see if it resolved it.

The history.json I dont have working but I raised that in another issue as its not in the source code

**Comment by vanlooverenkoen** [comment]
Can @mess110 change it back to the old version?

**Comment by vanlooverenkoen** [comment]
Where do you host your this website? And do you know where @mess110 hosts his server?

**Comment by jupiter50** [comment]
Well the old version has its flaws (and v6 can still be accessed - http://coinmarketcap.northpole.ro/api/v6/history/BTC_2017.json). The new version using IDs is more robust so we should wait till he is back from his holidays to try see if he can fix it rather than revert back.

I believe he hosts it here:
http://coinmarketcap.northpole.ro/

**Comment by vanlooverenkoen** [comment]
Is that one still updated till the latest 5 minutes?

**Comment by jupiter50** [comment]
The latest code generates v6 and v8 of the api. Both sets update every 5 mins I believe but also store it on a daily basis under each respective "history"

**Comment by vanlooverenkoen** [comment]
http://coinmarketcap.northpole.ro/ticker.json?identifier=bitcoin

Hasn't been updated in 2 days

**Comment by jupiter50** [comment]
Yes, I saw the same problem on my server. My server though has been updating the last 2 days (after my upgrade of the code). Probably need @mess110  to see why it sometimes fail as it seems random so far

**Comment by vanlooverenkoen** [comment]
@mess110 when do you think you can fix this?

**Comment by vanlooverenkoen** [comment]
I think it works again. What did you change?

**Comment by mess110** [comment]
Nothing yet, just landed still in plane. Will catch up and fix this today

**Comment by mess110** [comment]
Added some extra logging, but I can't explain the crash atm. Sorry for the inconveniences caused. I have been monitoring this for about 30 min and seems to work now. Please confirm if this is the case.

Will continue to keep an eye on this. More details will come once I have them

**Comment by vanlooverenkoen** [comment]
Yes it's working since yesterday morning. I don't know why but the data is updating since then.

**Comment by vanlooverenkoen** [comment]
Do you know what caused it?

**Comment by mess110** [comment]
There were crashes related to writing/reading to/from disk. Now I am catching those exceptions. In addition to this, I modified some code on production part of the experiment which caused more crashes. The 2nd part was fixed after doing a fresh deploy a few days ago.

Sry about the inconveniences
