### ISSUE TITLE
Where do you host?

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#24]
Where do you host your Ruby (ki) website? Heroku? 
If yes, what is your current dataplan?
Where do you host your db?
And what do you pay for it?

**Comment by mess110** [comment]
Not gonna give these details online, PM me if you want more details than this:

The server costs are around 10 USD (rounded) per month which I support myself and from donations. It is one of my hobby projects, not earning money off this.

Currently it takes about 220 seconds for the script to run.
