### ISSUE TITLE
Where did you get the currencyExchangeRates from?

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#25]
Where did you find the currencyExchangeRates on coinmarketcap?

**Comment by mess110** [comment]
There is a div with the id `currency-exchange-rates` on this page https://coinmarketcap.com/all/views/all/

the api does more than meets the eye ;)

Don't remember how I found it :P

**Comment by vanlooverenkoen** [comment]
So you only retrieve the usd values and then add the conversions form the currency-exchange-rates div? or do you realy retrieve all values form all currencies?

**Comment by mess110** [comment]
I convert because the values in the page are for usd and bitcoin only https://coinmarketcap.com/all/views/all/

Check the source on the all page.

"Funny" story time: At one point I would just take the values from the html page without looking if they are actually there. Because I had a too broad rescue, I didn't notice it.

**Comment by vanlooverenkoen** [comment]
https://coinmarketcap.com/all/views/all/#EUR
https://coinmarketcap.com/all/views/all/#JPY
...

Aah oke, because I am experiencing a little offset
example NEO
Coinmarketcap =>€15.73
And the API returns => €15.5848527828

**Comment by vanlooverenkoen** [comment]
Ok and now it is fixed, It seems like sometimes it takes a bit longer to refresh. Is that possible?

**Comment by mess110** [comment]
Yes, it takes slightly more than 3 minutes to run the script on the host I am using. Files are written one by one.

**Comment by vanlooverenkoen** [comment]
uhum, makes sense. Thank you again for your quick support. In a few weeks I will start experimenting with your ki framework. 👍

**Comment by mess110** [comment]
Cool! I built it as a prototyping framework to use at hackathons. If you have questions ask
