### ISSUE TITLE
Saturn: Name values get truncated

### ISSUE THREAD

**Issue by jupiter50** [mess110/coinmarketcap.northpole.ro#26]
For the "Name" field for each coin, some of the values get truncated. e.g
`"name": "Basic Attenti..."`

**Comment by mess110** [comment]
Hm.. This is a bug with `script.rb` as well. Pending fix after work

**Comment by mess110** [comment]
Ok this is fixed but you will see the effect only after history is written for tonight.

**Comment by mess110** [comment]
Ok, names are working as expected now :)

**Comment by jupiter50** [comment]
Great I'll take a look and give it some testing when my internet is fixed!
