### ISSUE TITLE
Saturn: Add Total field

### ISSUE THREAD

**Issue by jupiter50** [mess110/coinmarketcap.northpole.ro#27]
Can we add a "total" field on the JSON root structure? This total is the accumulative amount of coins listed in the JSON. Unfortunately I cant programmatically get the size of the array so need this field

**Comment by mess110** [comment]
Sure I can add that. This also feels like it needs some discussion.

I assume you are talking about the `coins` key. That is not an array, it is a hash. This means you can't call `length` but it allows you to do stuff like `json.coins.bitcoin` to get the value of Bitcoin.

To get all the keys of a hash you can do `Object.keys(json.coins)` or `Object.keys(json['coins'])`. This should return an array something like: `['bitcoin', 'dogecoin',....]`. On this you can call `length`.

```js
// lets say you make the request and the response is put in the json variable
var json = contents_of_saturn.json;

// you can get bitcoin like this:
console.log(json.coins.bitcoin.price.1day);

// or like this:
console.log(json['coins']['bitcoin']['price']['1day']);

// To get the total number of coins:
var keys = Object.keys(json['coins']);

// To iterate over each one:
for (var i = 0; i < keys.length; i++) {
    var key = keys[i];
    var specificCoin = json['coins'][key];
}
```

This is JS, I don't know the limitations of Google Sheets.

I am planning to add `total`, `active_currencies` and `active_assets` keys, stay tuned :)

**Comment by jupiter50** [comment]
You are absolutely right, it is a hash which is better than array anyway. Thanks for the tip, I'll try what you suggested!

**Comment by mess110** [comment]
Added a few new fields which should simplify things for you:

- `total`
- `active_assets`
- `active_currencies`
