### ISSUE TITLE
This website is under heavy load

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#28]
Can't access your api

http://coinmarketcap.northpole.ro/ticker.json?identifier=bitcoin,dogecoin

```
This website is under heavy load

We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.
```

**Comment by mess110** [comment]
Should be back now, I suspect crawling now takes more than 5 minutes, will need to optimize

**Comment by vanlooverenkoen** [comment]
any ideas why that is?

**Comment by mess110** [comment]
Slow and cheap hosting, but I just measured it and it took a little over 3 minutes. Still need to keep an eye on things

**Comment by vanlooverenkoen** [comment]
Perfect :)
