### ISSUE TITLE
site is down :(

### ISSUE THREAD

**Issue by ekerstein** [mess110/coinmarketcap.northpole.ro#32]

**Comment by mess110** [comment]
Damn the server, really can't take the load. Will have to reduce the number of crawls to once every 10 minutes until I find other options.

**Comment by mess110** [comment]
Back online

**Comment by ekerstein** [comment]
I pull 2017 data for about 200 different tickers once a day for my top 10 charts. I space the api calls out to 1 per second. Let me know if you want me to adjust anything.

**Comment by mess110** [comment]
Thanks @ekerstein, I appreciate your kindness.

But don't worry about it, I want to build an API which can resist all user needs/attacks. Besides in the past week, the server served over 2 million requests.

**Comment by ekerstein** [comment]
@mess110 Down again :(

**Comment by ekerstein** [comment]
@mess110 FYI, down again.
