### ISSUE TITLE
Is the site down?

### ISSUE THREAD

**Issue by marcoquerini** [mess110/coinmarketcap.northpole.ro#39]
It appears no responding

**Comment by marcoquerini** [comment]
*not responding*

**Comment by voidzero** [comment]
Yeah, it's been down for a week now. What's up, @mess110?

**Comment by mess110** [comment]
I restarted the server again. It is generating over 0.5 TB of traffic each month, it would be of great help if you can host your own version because my server just can't take it.

Regarding performance improvements: a different solution which doesn't write to disk in this way is required.

**Comment by marcoquerini** [comment]
would be possible to try to restart it again? now i can't get any response from the server...

**Comment by jupiter50** [comment]
Folks, as @mess110  politely requested, perhaps you can host it on your own server like I do? It is fairly easy to setup and far more performant that way. I use Cristian's site as a reference to spot check my data but probably can't be relied upon for production volumes.

I've asked in [issue 31](https://github.com/mess110/coinmarketcap.northpole.ro/issues/31) to prevent and identify server abusers

**Comment by voidzero** [comment]
I'll look into hosting my own. But I'm not that good with Ruby. How would you advice to put nginx in front of it? Use something like thin, perhaps?

**Comment by mess110** [comment]
I restarted the server.

I want to keep a good part of it free and I also want to provide a good service. I will offer a better alternative, but I need time to implement it (maybe between christmas and new year I can get something out).

I host it on nginx/apache2 (can't even remember), setup is quite straightforward. The app uses capistrano for deployment, I will create a docker image to make things simpler

**Comment by voidzero** [comment]
Thanks. I don't have docker on my server, but I can install it with rvm (ruby version manager) so that's not a problem. I just need to know how to run it.. I do know how to set up nginx as a proxy, I think. :smile:

**Comment by mess110** [comment]
For now, just try rvm and nginx, forget about docker. It would be of great help if you write step by step tutorial on how you did it, that way you would help me a lot because I can reference the link to other people who want to do the same.

At the moment there is only: https://github.com/mess110/coinmarketcap.northpole.ro/blob/master/INSTALL.md which is not very comprehensive. Try it out and tell me if you get stuck

**Comment by ekerstein** [comment]
That didn't last long :( Or did you take it back down?
