### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by LeighBicknell** [mess110/coinmarketcap.northpole.ro#41]
Looks like the site is down again. Is this traffic related?

I use this api frequently, and appreciate all of your hard work, so I'd like to offer to donate free hosting on one of my servers if this would be of any use?
Is the issue cpu or bandwidth related? What kind of specs are you currently running on?

Feel free to pm me if you'd like to discuss further?

**Comment by mess110** [comment]
![image](https://user-images.githubusercontent.com/226170/36351451-c7a846de-14b2-11e8-982e-26e79707921c.png)

Currently trying to reset it.

Imo, the best option would be to host this yourself for your own use. API usage is increasing, it would be great if the load could be distributed.

**Comment by LeighBicknell** [comment]
Thanks @mess110 !

I appreciate that hosting my own is an option, however this is more maintenance and work on my (and other people's ends)
Would you be interested in a donated dedicated server for coinmarketcap.northpole.ro?
Looks like memory issues, how much RAM does your current hosting have?

**Comment by mess110** [comment]
Wow very generous thank you.

I will gladly set it up and maintain it, but on a different domain, I have other plans for northpole.ro . It would be like a mirror, which is a good thing.

It is running on 1GB of ram, but it is not enough

**Comment by FlickerBean** [comment]
@mess110 Can we talk via email?

elwon20 at -removethisbit-gmail dot com
