### ISSUE TITLE
Paging the API

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#5]
Hi, 

I love your API but I was thinking. Is it possible to add paging to the all API endpoint? The json is to big at the moment. It would be nice to load the first 20 and at a later time the next 20 by adding an offset.

http://coinmarketcap.northpole.ro/api/v6/all.json?limit=20
http://coinmarketcap.northpole.ro/api/v6/all.json?limit=20&offset=20
http://coinmarketcap.northpole.ro/api/v6/all.json?page=3&size=20

if I had any ruby experience I wrote it myself but I have no idea where to start. I'm implementing it in an Android App

**Comment by mess110** [comment]
http://coinmarketcap.northpole.ro/api.json?page=0
http://coinmarketcap.northpole.ro/api.json?page=0&size=20

Default page is 0
Default size is 20
I am also returning the total number of pages in `total_pages`

Please keep in mind this was a really fast implementation and I didn't do proper testing. Maybe you can help me test it.

Also, I didn't document it yet.
