### ISSUE TITLE
Get info of some Coins instead of 1

### ISSUE THREAD

**Issue by vanlooverenkoen** [mess110/coinmarketcap.northpole.ro#6]
Hi,

I need an endpoint so I can make 1 request to get some Coin details.
like

http://coinmarketcap.northpole.ro/api/v6/all?list=[BTC,ETH]
http://coinmarketcap.northpole.ro/api/v6/coins?list=[BTC,ETH,LTC]

is this possible? If I had any experience with Ruby I wrote it myself. But I do want to help you if necessary

**Comment by mess110** [comment]
http://coinmarketcap.northpole.ro/api.json?select=BTC,ETH
http://coinmarketcap.northpole.ro/api.json?select[]=BTC&select[]=ETH

Both do the same thing. If you can, please test :)
